config/routes.rb
Youlister::Application.routes.draw do
  resources :logins

  resources :videos

 root 'videos#index'

end

app/models/login.rb
class Login < ActiveRecord::Base
belongs_to :video
end

app/models/video.rb
class Video < ActiveRecord::Base
  require 'json'
  require 'open-uri'
  has_many :logins
  before_save  :gettitle

  def gettitle
    url = "https://www.googleapis.com/youtube/v3/videos?part=snippet&id=" + self.youID + "&part=contentDetails&key=token"
    begin
    doc = JSON.parse(open(url))
    self.title=doc.items[0].snipet.title
    rescue OpenURI::HTTPError => ex
      self.title = "Handle missing video here"
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

 def import
    @video = Video.new
    fichier = File.open("ID.txt", "r")
    i = 1
    fichier.each_line { |ligne|
      @video.youID =ligne
      @video.create
    }
    fichier.close
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render action: 'show', status: :created, location: @login }
      else
        format.html { render action: 'new' }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:name, :youID, :count)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]



  # GET /videos
  # GET /videos.json
  def index
    sort_by = params[:sort_by] || "count"
    @q = Video.search params[:q]
    @videos = @q.result.order("#{sort_by} DESC").paginate(:page => params[:page], :per_page => 18)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
  end

  # GET /videos/new
  def new
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.find_or_create_by(:youID => video_params[:youID])

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render action: 'show', status: :created, location: @video }
      else
        format.html { render action: 'new' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :youID, :comment, :count)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Youlister</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :youID %><br>
    <%= f.number_field :youID %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.number_field :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<h1>Listing logins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Youid</th>
      <th>Count</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.name %></td>
        <td><%= login.youID %></td>
        <td><%= login.count %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @login.name %>
</p>

<p>
  <strong>Youid:</strong>
  <%= @login.youID %>
</p>

<p>
  <strong>Count:</strong>
  <%= @login.count %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :youID %><br>
    <%= f.text_field :youID %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment %>
  </div>
  <div class="field">
    <%= f.label :count %><br>
    <%= f.text_area :count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/videos/edit.html.erb
<h1>Editing video</h1>

<%= render 'form' %>

<%= link_to 'Show', @video %> |
<%= link_to 'Back', videos_path %>

app/views/videos/index.html.erb
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>

<h1>VIDEOS OF THE WORLD</h1>

 <div id="menu">
   <ul id="onglets">
     <li class="<%= 'active' if params[:sort_by] == 'count' %>"><%= link_to "C'est de la bombe bébé", videos_path(sort_by: "count")  %></li>
     <li class="<%= 'active' if params[:sort_by] == 'updated_at' %>"><%= link_to "Ça vient de tomber", videos_path(sort_by: "updated_at")  %></li>
     <li ><%= link_to "Surprends moi lapin", videos_path(page: 1 + rand(@videos.count()/18) )  %></li>
     <li ><%= link_to "Russian Roulette", "https://www.youtube.com/watch?v="+Video.first(:offset => rand(@videos.count)).youID  %></li>
     <li class="search"><%= search_form_for @q do |f| %>
  <%= f.search_field :title_cont, :placeholder => "viens chercher bonheur...", :id=>"search_field" %>
  <%= f.submit :value=>"Recherche", :id=>"search_button" %>
<% end %></li>
   </ul>
<%= will_paginate @videos %>
 </div>

<div class="corps">



<!-- <table> -->
<!--   <thead> -->
<!--     <tr> -->
<!--       <th>Nom</th> -->
<!--       <th>Thumbnail</th> -->
<!--       <th></th> -->
<!--       <th></th> -->
<!--       <th></th> -->
<!--     </tr> -->
<!--   </thead> -->

<!--   <tbody> -->
    <% @videos.each do |video| %>

      <div class="thumbnails" style="background-image:url('<%="http://i.ytimg.com/vi/"+video.youID+"/0.jpg"%>')";>
	<div class="count"><%=video.count%></div>
	
	<div class="title">
<p><%=video.title%></p>
	  <a href= "https://www.youtube.com/watch?v=<%=video.youID %>"> </a>

	</div>
      </div>
      
      
      <!-- <tr> -->
      <!--   <td><%= link_to video.title, "https://www.youtube.com/watch?v="+video.youID %></td> -->
      <!--   <td><%= image_tag("http://i.ytimg.com/vi/"+video.youID+"/0.jpg")  %></td> -->
      <!-- 	<td> -->
      <!-- 	  <% Login.find_all_by_youID(video.youID).each do |nick|  %> -->
      <!-- 	    <div><%=nick.name%> -->
      <!-- 	      <%= nick.count%></div> -->
      <!-- 	  <% end %> -->
      <!-- 	</td> -->
      <!-- 	<td><%= video.count %></td> -->
      <!-- 	<td><%= link_to 'Show', video %></td> -->
      <!--   <td><%= link_to 'Edit', edit_video_path(video) %></td> -->
      <!--   <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      <!-- </tr> -->
    <% end %>
<!--   </tbody> -->
<!-- </table> -->
</div>

</div>
<br>

    <script type="text/javascript">  
      var positionElementInPage = $("#menu").offset().top;
      $(window).scroll(
        function() {
          if ($(window).scrollTop() >= positionElementInPage) {
            // fixed
            $('#menu').addClass("floatable");
          } else {
            // relative
            $('#menu').removeClass("floatable");
          }
        }
      );
    </script>

app/views/videos/new.html.erb
<h1>New video</h1>

<%= render 'form' %>

<%= link_to 'Back', videos_path %>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Youid:</strong>
  <%= @video.youID %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @video.comment %>
</p>
<p>
  <strong>Count:</strong>
  <%= @video.count %>
</p>

<%= link_to 'Edit', edit_video_path(@video) %> |
<%= link_to 'Back', videos_path %>